# Generated by Django 3.1.7 on 2021-03-15 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('house_no', models.CharField(max_length=100)),
                ('house_size', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('bedrooms', models.CharField(max_length=50)),
                ('bathrooms', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('listing_type', models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=80)),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Thika', 'Thika'), ('Nakuru', 'Nairobi')], max_length=255)),
                ('geo_location', models.CharField(max_length=255, null=True)),
                ('main_photo', models.ImageField(upload_to='listing_photos/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('booked', 'booked'), ('sold', 'sold'), ('open', 'open')], max_length=100)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_photo', models.ImageField(upload_to='listing_photos/%Y/%m/%d')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.listing')),
            ],
        ),
    ]
