# Generated by Django 3.1.7 on 2021-03-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_listing_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'permissions': (('can_create_listing', 'can_create_listing'),)},
        ),
    ]
