# Generated by Django 3.1.7 on 2021-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auto_20210316_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='agent_house_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='from_agent_subdomain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
